config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  root :to =>'static_pages#home'
  get '/registrado',to: 'static_pages#later_register', as: :registrado

  namespace :admin do
    resources :modalidad_servicios
  end
  namespace :estadistica_module do
    get '/modalidad/todos/estados', to: 'estadistica#modalidad_estado_all', as: :modalidad_estado_all
    get '/modalidad/cupo/estados', to: 'estadistica#modalidad_cupo_autorizado', as: :modalidad_cupo_autorizado
    post '/modalidad/estado', to: 'estadistica#modalidad_estado', as: :modalidad_estado
    post '/modalidad/parroquias', to: 'estadistica#modalidad_parroquias', as: :modalidad_parroquias
    post '/modalidad/ciudad', to: 'estadistica#modalidad_ciudad', as: :modalidad_ciudad
    get '/modalidad/estado/seleccion', to: 'estadistica#selector_ano_modalidad', as: :selector_ano_modalidad
    get '/modalidad/parroquias/seleccion', to: 'estadistica#selector_parroquias', as: :selector_parroquias
    get '/modalidad/ciudad/seleccion', to: 'estadistica#selector_ciudad', as: :selector_ciudad
    post '/unidades/todos/estado/', to: 'estadistica#vencimiento_flota', as: :vencimiento_flota
    get '/vencimiento/ano/seleccion/flota',to: 'estadistica#selector_ano_vencimiento_flota', as: :selector_ano_vencimiento_flota
    get '/vencimiento/ano/seleccion/cps',to: 'estadistica#selector_ano_vencimiento_cps', as: :selector_ano_vencimiento_cps
    post '/vencimiento/ano/cps', to: 'estadistica#vencimiento_cps', as: :vencimiento_cps
    get '/vistas/estados/modalidad', to: 'estadistica#vistas_estados', as: :vistas_estados
    get '/selector/proximas/vencer/flota/', to: 'estadistica#selector_proximas_vencer_flota', as: :selector_proximas_vencer_flota
    post '/proximas/vencer/flota/', to: 'estadistica#proximas_vencer_flota', as: :proximas_vencer_flota
    get '/modalidad/estados/tipounidad/', to: 'estadistica#selector_estados_tipo_unidad', as: :selector_estados_tipo
    post '/modalidad/tipounidad', to: 'estadistica#modalidad_tipo_unidad', as: :modalidad_tipo_unidad
    get '/form/igual/parada/', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/estadistica/igual/parada/', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    get '/meses/seleccion/historicos', to: 'estadistica#selector_meses_historicos', as: :selector_meses_historicos
    post '/tramites/historicos', to: 'estadistica#nro_tramites_realizados_historicos', as: :tramites_historicos
    post '/vistas/parroquias', to: 'estadistica#vistas_parroquias', as: :vistas_parroquias
    post '/vistas/ciudad', to: 'estadistica#vistas_ciudad', as: :vistas_ciudad
  end

  scope module: 'listas' do
    post '/operadoras/listadas/rutas', to: 'listado#listar_por_rutas', as: :listar_por_rutas
    get '/creador/rutas/buscar', to: 'listado#creador_rutas_buscar', as: :creador_rutas
    get '/operadoras/index/', to: 'listado#index_operadora', as: :index_operadora
    get '/operadora/igual/parada', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/resultado/igual/parada', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    post '/operadoras/est/mod', to: 'listado#index_operadora_est_mod', as: :index_est_mod
    post '/operadoras/vencimiento/mes', to: 'listado#index_operadora_mes_ven', as: :index_op_mes_venc
    post '/operadoras/tipounidadvehicular', to: 'listado#index_operadora_tipo_unidad', as: :index_tipo_unidad
    post '/operadoras/vencimiento/mes/cps', to: 'listado#index_op_mes_cps', as: :index_op_mes_cps
    post '/operadoras/igual/parada', to: 'listado#index_op_igual_par', as: :index_op_igual_parada
    post '/operadoras/flota/vencer', to: 'listado#index_ope_flo_venc', as: :index_op_fl_vencer
  end

  namespace :horario_d do
    # get '/index/', to: 'horarios#index', as: :index
    get '/index/', to: 'horarios_dinamico#index', as: :index
    get '/new/', to: 'horarios#new', as: :new
    get '/edit/:id', to: 'horarios#edit', as: :edit
    post '/create/', to: 'horarios#create', as: :create
    patch '/update/:id', to: 'horarios#update', as: :update
    delete '/destroy/:id', to: 'horarios#destroy', as: :destroy
    get '/show/:id', to: 'horarios#show', as: :show
    get 'consultar/show/:id', to: 'horarios#consultar_show', as: :consultar
    post '/horarios/guardar/', to: 'horarios_dinamico#crear_horario', as: :crear_horario
    get '/horarios/eliminar/horario/:id', to: 'horarios_dinamico#eliminar_horario', as: :eliminar_horario_lista
  end

  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena', to: 'session_users/sessions#edit_password'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    post 'reestablecer_password',
                    to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
      { :registrations => 'session_users/registrations',
        :sessions =>'session_users/sessions',
        :passwords => 'session_users/passwords'}

  namespace :operadora do
    get '/index/', to: 'operadora_transporte_ps#index', as: :index
    get '/new/', to: 'operadora_transporte_ps#new', as: :new
    get '/edit/:id', to: 'operadora_transporte_ps#edit', as: :edit
    post '/create/', to: 'operadora_transporte_ps#create', as: :create
    patch '/update/:id', to: 'operadora_transporte_ps#update', as: :update
    delete '/destroy/:id', to: 'operadora_transporte_ps#destroy', as: :destroy
    get '/show/:id', to: 'operadora_transporte_ps#show', as: :show
    get '/consultar/', to: 'operadora_transporte_ps#consultar', as: :consultar
    post 'ciudad_municipio', to: 'operadora_transporte_ps#ciudad_municipio', as: :ciudad_municipio
  end
  namespace :servicio do
    get '/index/consulta', to: 'servicio_operadora_cs#index_consulta', as: :index_consulta
    get '/index/', to: 'servicio_operadora_cs#index', as: :index
    get '/new/', to: 'servicio_operadora_cs#new', as: :new
    get '/edit/:id', to: 'servicio_operadora_cs#edit', as: :edit
    post '/create/', to: 'servicio_operadora_cs#create', as: :create
    patch '/update/:id', to: 'servicio_operadora_cs#update', as: :update
    delete '/destroy/:id', to: 'servicio_operadora_cs#destroy', as: :destroy
    get '/show/:id', to: 'servicio_operadora_cs#show', as: :show
    get '/show/consulta/:id', to: 'servicio_operadora_cs#show_consulta', as: :show_consulta
    post '/end/', to: 'servicio_operadora_cs#end_carga', as: :end_carga
    post '/set_codigo_rotp/', to: 'servicio_operadora_cs#set_codigo_rotp', as: :set_codigo_rotp
  end

  namespace :historico do
    get '/index', to: 'historico_solicitudes_aprobs#index', as: :index
    # get '/new/', to: 'historico_solicitudes_aprobs#new', as: :new
    get '/edit/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#edit', as: :edit
    post '/create/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#create', as: :create
    patch '/update/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#update', as: :update
    delete '/destroy/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#destroy', as: :destroy
    get '/show/:id', to: 'historico_solicitudes_aprobs#show',as: :show
    get '/consulta/final', to: 'historico_solicitudes_aprobs#consulta',as: :consulta
    get 'verificar/regreso', to: 'historico_solicitudes_aprobs#verificar_regreso', as: :verificar_regreso
    # get '/show/:id', to: 'historico_solicitudes_aprobs#show', as: :show
  end

  namespace :asegurador do
    get '/index/', to: 'aseguradoras#index', as: :index
    get '/edit/:id', to: 'aseguradoras#edit', as: :edit
    post '/create/', to: 'aseguradoras#create', as: :create
    patch '/update/:id', to: 'aseguradoras#update', as: :update
    delete '/destroy/:id', to: 'aseguradoras#destroy', as: :destroy
    post '/rif/', to: 'aseguradoras#rif_aseguradora', as: :rif_a
  end

  namespace :flota_d do
    get '/index/', to: 'flota#index', as: :index
    get '/new/', to: 'flota#new', as: :new
    get '/edit/:id', to: 'flota#edit', as: :edit
    post '/create/', to: 'flota#create', as: :create
    patch '/update/:id', to: 'flota#update', as: :update
    delete '/destroy/:id', to: 'flota#destroy', as: :destroy
    get '/show/:id', to: 'flota#show', as: :show
  end

  namespace :seguro do
    get '/index/', to: 'seguro_vehiculos#index', as: :index
    get '/new/', to: 'seguro_vehiculos#new', as: :new
    get '/edit/:id', to: 'seguro_vehiculos#edit', as: :edit
    post '/create/', to: 'seguro_vehiculos#create', as: :create
    patch '/update/:id', to: 'seguro_vehiculos#update', as: :update
    delete '/destroy/:id', to: 'seguro_vehiculos#destroy', as: :destroy
    get '/show/:id', to: 'seguro_vehiculos#show', as: :show
  end

  namespace :ruta_flota do
    get '/index/', to: 'ruta#index', as: :index
    get '/new/', to: 'ruta#new', as: :new
    get '/edit/:id', to: 'ruta#edit', as: :edit
    post '/create/', to: 'ruta#create', as: :create
    patch '/update/:id', to: 'ruta#update', as: :update
    delete '/destroy/:id', to: 'ruta#destroy', as: :destroy
    get '/show/:id', to: 'ruta#show', as: :show
    get '/new_taxi/', to: 'ruta#new_taxi', as: :new_taxi
    get '/edit_taxi/:id', to: 'ruta#edit_taxi', as: :edit_taxi
    patch '/update_taxi/:id', to: 'ruta#update_taxi', as: :update_taxi
    post '/create/taxi', to: 'ruta#create_taxi', as: :create_taxi
    get 'nueva/parada', to: 'ruta#nueva_parada', as: :nueva_parada
    post 'guardar/parada', to: 'ruta#guardar_parada', as: :guardar_parada
  end

  namespace :localizacion_select do
    post 'lista/municipios', to: 'busquedas#estado_municipios', as: 'estado_municipios'
    post 'lista/ciudades', to: 'busquedas#estado_ciudades', as: 'estado_ciudades'

app/controllers/static_pages_controller.rb
# -*- encoding : utf-8 -*-
class StaticPagesController < ApplicationController
  # before_action :deshabilitar_wizard, only: [:home]
  helper_method :resource, :resource_name, :devise_mapping
  def home
    if session_user_signed_in?
      @operadoras = current_session_user.usuario.operadora_transporte_ps
      current_session_user.usuario.operadora_transporte_ps.each do |op|
        op.servicio_operadora_cs.each do |s|
          if !s.completado
            return @incompleto = false
          end
        end
      end
      @incompleto = true
    end
  end

  def later_register
    @usuario_sput = UsuarioSput.find_by(id: params[:id])
  end

 end

app/views/static_pages/_form.html.haml
.panel.panel-default
  .panel-body
    %h4 Usuarios Registrados
    = form_for(resource, as: resource_name, url: session_path(resource_name), html: {class: "form form-signup", role: "form"}) do |f|
      .form-group
        .input-group
          .input-group-addon.input_gris
            %i.fa.fa-user.icon-color
          = f.text_field :email, :class=>"form-control", :placeholder=>"Email", :required =>'required', autofocus: true
      .form-group
        .input-group
          .input-group-addon.input_gris
            %i.fa.fa-lock.icon-color
          = f.password_field :password, :class=>"form-control", :placeholder=>"Contraseña", :required =>'required', autocomplete: "off"
      .form-group
        - if devise_mapping.rememberable?
          = f.check_box :remember_me
          = f.label :remember_me, 'Mantener Conectado'

      .row
        .col-md-6
          = f.submit "Entrar", class: 'btn btn-success btn-block'
        .col-md-6
          - if devise_mapping.registerable? && controller_name != 'registrations'
            = link_to "Registrarse!", registro_path,  "data-no-turbolink" => true
      .row
        .col-md-12
          %br/
          - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
            = link_to "¿Olvido su contraseña?", recuperar_contrasena_path
      .row
        .col-md-12
          - if devise_mapping.confirmable? && controller_name != 'confirmations'
            = link_to "¿No recibió el correo de confirmación?", new_confirmation_path(resource_name)
            %br/

app/views/static_pages/_logued.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-md-10
    %h2
      Inicio
    %ol.breadcrumb
      %li.text-navy
        %b
          Inicio
      %li
- if !@incompleto
  .wrapper.wrapper-content.animated.fadeInUp
    .row
      .col-md-12
        .ibox.float-e-margins
          .ibox-content
            %div.text-center
              %h3
                %b
                  ¡ATENCIÓN!...
              %h4
                POSEE SERVICIOS EN LOS QUE AUN NO HA COMPLETADO EL REGISTRO.
            %table.table.table-striped.table-bordered.table-condensed
              %thead
                %tr.info.darked
                  %th
                    Operadora
                  %th
                    Modalidad del Servicio
                  %th
                    Código ROTP
                  %th
                    Estatus
                  %th
                    Acciones
              %tbody
                - @operadoras.each do |operadora|
                  - operadora.servicio_operadora_cs.each do |servicio|
                    - unless servicio.completado
                      %tr
                        %td.text-left
                          = operadora.razon_social
                        %td.text-left
                          = servicio.modalidad_servicio.nombre
                        %td.text-left
                          = servicio.codigo_rotp
                        %td.text-left.text-danger
                          Sin Completar Registro
                          %i.fa.fa-times
                        %td.text-left
                          = link_to  servicio_edit_path(servicio) do
                            Continuar Registro de Servicio
                            %i.fa.fa-car
            %p.text-muted
              *Recuerde que para completar la carga de la data, debe guardar: Rutas, Flota, Vehículos, Seguro,
              Toques o Paradas, Horario(si aplica) e Histórico de Solicitudes Aprobadas
- if current_session_user.usuario.operadora_transporte_ps.joins(:servicio_operadora_cs).where(servicio_operadora_cs: { completado: true }).any?
  .wrapper.wrapper-content.animated.fadeInRight
    - if @operadoras.any?
      - @operadoras.each do |op|
        - if op.servicio_operadora_cs.any?
          .row
            .col-md-12
              .ibox.float-e-margins
                .ibox-title
                  %h3
                    Lista de Modalidades de Servicio - Operadora
                    %b
                      = op.razon_social
                .ibox-content

                  -#= link_to servicio_new_path(id: op.id), class: 'btn' do
                    %i.fa.fa-plus
                    Nueva Modalidad para operadora
                    = op.razon_social
                  %table.table.table-striped.table-bordered.table-condensed
                    %thead
                      %tr
                        %th.text-center
                          Código ROTP
                        %th.text-center
                          Modalidad del Servicio
                        %th.text-center
                          Estatus
                        -#%th.text-center
                          Opción
                    %tbody
                      - op.servicio_operadora_cs.each do |servicio|
                        %tr
                          %td.text-center
                            = servicio.codigo_rotp
                          %td.text-center
                            = servicio.modalidad_servicio_val
                          - if servicio.completado
                            %td.text-center.text-primary
                              Registro Completo
                              %i.fa.fa-check
                          - else
                            %td.text-center.text-danger
                              Registro Incompleto
                              %i.fa.fa-times
                          -#%td.text-center
                            = link_to servicio_show_consulta_path(servicio,tipo: params[:tipo]),{"data-no-turbolink" => "", title: 'Consultar', rel: 'tooltip'} do
                              %i.fa.fa-search
                            &nbsp;
                            &nbsp;
                            - if servicio.completado
                              = link_to servicio_edit_path(servicio,tipo: params[:tipo]),{"data-no-turbolink" => "", title: 'Editar', rel: 'tooltip'} do
                                %i.fa.fa-edit
                                Editar
                            - else
                              = link_to  servicio_edit_path(servicio), {"data-no-turbolink" => "", title: 'Continuar Registro', rel: 'tooltip'} do
                                %i.fa.fa-car
                                Continuar Registro

    - else
      .row
        .col-md-12
          .ibox.float-e-margins
            .ibox-content.text-center
              %h3
                No posee operadoras de transporte registradas.
              %br
              = link_to operadora_new_path, class: 'btn btn-success' do
                %i.fa.fa-plus
                Agregar Nueva Operadora de Transporte de Personas



  -#.row
  -#  .col-md-12
  -#    .ibox.float-e-margins
  -#      .ibox-title
  -#        %h3
  -#          Modalidades de Servicio Registradas
  -#      .ibox-content
  -#        .table-responsive
  -#          %table.table-striped.table-bordered.table-condensed.table
  -#            %thead
  -#              %tr.info.darked
  -#                %th
  -#                  Operadora
  -#                %th
  -#                  Modalidad del Servicio
  -#                %th
  -#                  Código ROTP
  -#                %th
  -#                  Estatus
  -#                %th
  -#                  Acciones
  -#            %tbody
  -#              - current_session_user.usuario.operadora_transporte_ps.each do |operadora|
  -#                - operadora.servicio_operadora_cs.each do |servicio|
  -#                  - if servicio.completado
  -#                    %tr
  -#                      %td.text-left
  -#                        = operadora.razon_social
  -#                      %td.text-left
  -#                        = servicio.modalidad_servicio.nombre
  -#                      %td.text-left
  -#                        = servicio.codigo_rotp
  -#                      %td.text-primary
  -#                        Registro Completo
  -#                        %i.fa.fa-check
  -#                      %td.text-left
  -#                        = link_to  servicio_edit_path(servicio) do
  -#                          %i.fa.fa-edit
  -#                          Editar



.row
  .col-md-12
    .ibox.float-e-margins
      .ibox-content.text-center
        .row
          .col-lg-12
            = image_tag 'bienvenidos_usuarios.png'

app/views/static_pages/_not_logued.html.haml
.row.border-bottom.white-bg.dashboard-header
  .col-lg-10.col-lg-offset-1
    .row
      .col-md-8
        #myCarousel.carousel.slide
          / Indicators
          %ol.carousel-indicators
            %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
            %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
          / Wrapper for slides
          .carousel-inner
            #slide1.item.active
              .carousel-caption
            / end carousel-caption
            / end item
            #slide2.item
              .carousel-caption
            / end carousel-caption
            / end item
            #slide3.item
              .carousel-caption
          / end carousel-caption
          / end item
          / carousel-inner
          / Controls
          %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel"}
            %span.icon-prev
          %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel"}
            %span.icon-next
      / end myCarousel
      / end col-md-8
      / login
      .col-md-4
        = render 'form'
.row.graylight-bg
  .col-lg-12
    .wrapper
      -#.row
      -#  .col-lg-10.col-lg-offset-1
      -#    .row
      -#      .col-lg-4
      -#        .well.well-lg.c1
      -#          .row
      -#            .col-sm-4
      -#              = link_to root_url, class: 'link_index' do
      -#                = image_tag 'medico.png', class: 'btn_img'
      -#            .col-md-8
      -#              %br/
      -#              = link_to 'Buscador de Médicos/Psicólogos', root_url, class: 'link_index'
      -#      .col-lg-4
      -#        .well.well-lg.c2
      -#          .row
      -#            .col-sm-4
      -#              = link_to root_url, class: 'link_index' do
      -#                = image_tag 'centro_de_salud.png', class: 'btn_img'
      -#            .col-md-8
      -#              %br/
      -#              = link_to 'Buscador de Centro de Salud', root_url, class: 'link_index'
      -#      .col-lg-4
      -#        .well.well-lg.c3
      -#          .row
      -#            .col-sm-4
      -#              = link_to root_url, class: 'link_index' do
      -#                = image_tag 'centro_de_examenes.png', class: 'btn_img'
      -#            .col-md-8
      -#              %br/
      -#              = link_to 'Buscador de Exámenes', root_url, class: 'link_index'
      .row
        .col-lg-10.col-lg-offset-1

          .row
            .col-lg-4
              .well.well-lg.c4
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'transporte.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Requisitos', root_url, class: 'link_index'
            / end well c4
            .col-lg-4
              .well.well-lg.c5
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'servicios.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Servicios', root_url, class: 'link_index'
            / end well c5
            .col-lg-4
              .well.well-lg.c6
                .row
                  .col-sm-4
                    = link_to root_url, class: 'link_index' do
                      = image_tag 'noticias.png', class: 'btn_img'
                  .col-md-8
                    %br/
                    = link_to 'Noticias', root_url, class: 'link_index'

-#%footer
-#  #footer
-#    .row.graydark-bg
-#      .col-lg-12
-#        .row
-#          .col-md-1
-#          .col-md-2.verticaline
-#            %ul.nav.nav-pills.nav-stacked
-#              %li.titulo_footer Nuestra Institución
-#              %li.link_footer
-#                %a{:href => "#"} Nuestros Clientes
-#              %li.link_footer
-#                %a{:href => "#"} Acerca de la Institución
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#          .col-md-2.verticaline
-#            %ul.nav.nav-pills.nav-stacked
-#              %li.titulo_footer Directorio
-#              %li.link_footer= link_to 'Médicos', root_url
-#              %li.link_footer= link_to 'Centro de Salud', root_url
-#              %li.link_footer= link_to 'Centro de Exámenes', root_url
-#          .col-md-2.verticaline
-#            %ul.nav.nav-pills.nav-stacked
-#              %li.titulo_footer Promociones
-#              %li.link_footer
-#                %a{:href => "#"} Medicamentos
-#              %li.link_footer
-#                %a{:href => "#"} Exámenes
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#                %br/
-#          .col-md-2.verticaline
-#            %ul.nav.nav-pills.nav-stacked
-#              %li.titulo_footer Actualidad
-#              %li.link_footer
-#                %a{:href => "#"} Eventos
-#              %li.link_footer
-#                %a{:href => "#"} Noticias
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#              %li.link_footer
-#                %a{:href => "#"}
-#                %br/
-#          .col-md-2
-#            %ul.nav.nav-pills.nav-stacked
-#              %li.titulo_footer Contacto
-#              %li.link_footer
-#                %a{:href => "#"} ¿Quiénes Somos?
-#              %li.link_footer
-#                %a{:href => "#"} Contáctanos
-#              %li.link_footer
-#                %a{:href => "#"} Danos tu Opinión
-#              %li.link_footer
-#                %a{:href => "#"} Preguntas Frecuentes
-#                %br/
-#              %li.link_footer
-#                %a{:href => "#"}
-#                %br/
-#          .col-md-1

app/views/static_pages/home.html.haml
- if session_user_signed_in?
  = render partial: 'logued'
- else
  = render partial: 'not_logued'

app/views/static_pages/later_register.html.haml
.container
  .row
    .col-xs-12
      %br/
      %br/
      %br/
      %h3
        = "Sr(a).  " "#{@usuario_sput.nombre} #{@usuario_sput.apellido}"
        %br/
        %br/
        %br/
      %span.message
        %span.fa.fa-check
        Se ha registrado sastifactoriamente.
        %br/
      %span.text-justify
        %br/
        %br/
        Para verificar su cuenta, debe ingresar a su correo.
        Si nos has recibido un correo electrónico dentro de unos minutos, por favor revise en las carpetas "spam ó correo no deseado".
        Si tiene problemas para verificar por email por favor
        %strong Contáctenos
        para asistencia.
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/
        %br/