config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  root :to =>'static_pages#home'
  get '/registrado',to: 'static_pages#later_register', as: :registrado

  namespace :admin do
    resources :modalidad_servicios
  end
  namespace :estadistica_module do
    get '/modalidad/todos/estados', to: 'estadistica#modalidad_estado_all', as: :modalidad_estado_all
    get '/modalidad/cupo/estados', to: 'estadistica#modalidad_cupo_autorizado', as: :modalidad_cupo_autorizado
    post '/modalidad/estado', to: 'estadistica#modalidad_estado', as: :modalidad_estado
    post '/modalidad/parroquias', to: 'estadistica#modalidad_parroquias', as: :modalidad_parroquias
    post '/modalidad/ciudad', to: 'estadistica#modalidad_ciudad', as: :modalidad_ciudad
    get '/modalidad/estado/seleccion', to: 'estadistica#selector_ano_modalidad', as: :selector_ano_modalidad
    get '/modalidad/parroquias/seleccion', to: 'estadistica#selector_parroquias', as: :selector_parroquias
    get '/modalidad/ciudad/seleccion', to: 'estadistica#selector_ciudad', as: :selector_ciudad
    post '/unidades/todos/estado/', to: 'estadistica#vencimiento_flota', as: :vencimiento_flota
    get '/vencimiento/ano/seleccion/flota',to: 'estadistica#selector_ano_vencimiento_flota', as: :selector_ano_vencimiento_flota
    get '/vencimiento/ano/seleccion/cps',to: 'estadistica#selector_ano_vencimiento_cps', as: :selector_ano_vencimiento_cps
    post '/vencimiento/ano/cps', to: 'estadistica#vencimiento_cps', as: :vencimiento_cps
    get '/vistas/estados/modalidad', to: 'estadistica#vistas_estados', as: :vistas_estados
    get '/selector/proximas/vencer/flota/', to: 'estadistica#selector_proximas_vencer_flota', as: :selector_proximas_vencer_flota
    post '/proximas/vencer/flota/', to: 'estadistica#proximas_vencer_flota', as: :proximas_vencer_flota
    get '/modalidad/estados/tipounidad/', to: 'estadistica#selector_estados_tipo_unidad', as: :selector_estados_tipo
    post '/modalidad/tipounidad', to: 'estadistica#modalidad_tipo_unidad', as: :modalidad_tipo_unidad
    get '/form/igual/parada/', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/estadistica/igual/parada/', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    get '/meses/seleccion/historicos', to: 'estadistica#selector_meses_historicos', as: :selector_meses_historicos
    post '/tramites/historicos', to: 'estadistica#nro_tramites_realizados_historicos', as: :tramites_historicos
    post '/vistas/parroquias', to: 'estadistica#vistas_parroquias', as: :vistas_parroquias
    post '/vistas/ciudad', to: 'estadistica#vistas_ciudad', as: :vistas_ciudad
  end

  scope module: 'listas' do
    post '/operadoras/listadas/rutas', to: 'listado#listar_por_rutas', as: :listar_por_rutas
    get '/creador/rutas/buscar', to: 'listado#creador_rutas_buscar', as: :creador_rutas
    get '/operadoras/index/', to: 'listado#index_operadora', as: :index_operadora
    get '/operadora/igual/parada', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/resultado/igual/parada', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    post '/operadoras/est/mod', to: 'listado#index_operadora_est_mod', as: :index_est_mod
    post '/operadoras/vencimiento/mes', to: 'listado#index_operadora_mes_ven', as: :index_op_mes_venc
    post '/operadoras/tipounidadvehicular', to: 'listado#index_operadora_tipo_unidad', as: :index_tipo_unidad
    post '/operadoras/vencimiento/mes/cps', to: 'listado#index_op_mes_cps', as: :index_op_mes_cps
    post '/operadoras/igual/parada', to: 'listado#index_op_igual_par', as: :index_op_igual_parada
    post '/operadoras/flota/vencer', to: 'listado#index_ope_flo_venc', as: :index_op_fl_vencer
  end

  namespace :horario_d do
    # get '/index/', to: 'horarios#index', as: :index
    get '/index/', to: 'horarios_dinamico#index', as: :index
    get '/new/', to: 'horarios#new', as: :new
    get '/edit/:id', to: 'horarios#edit', as: :edit
    post '/create/', to: 'horarios#create', as: :create
    patch '/update/:id', to: 'horarios#update', as: :update
    delete '/destroy/:id', to: 'horarios#destroy', as: :destroy
    get '/show/:id', to: 'horarios#show', as: :show
    get 'consultar/show/:id', to: 'horarios#consultar_show', as: :consultar
    post '/horarios/guardar/', to: 'horarios_dinamico#crear_horario', as: :crear_horario
    get '/horarios/eliminar/horario/:id', to: 'horarios_dinamico#eliminar_horario', as: :eliminar_horario_lista
  end

  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena', to: 'session_users/sessions#edit_password'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    post 'reestablecer_password',
                    to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
      { :registrations => 'session_users/registrations',
        :sessions =>'session_users/sessions',
        :passwords => 'session_users/passwords'}

  namespace :operadora do
    get '/index/', to: 'operadora_transporte_ps#index', as: :index
    get '/new/', to: 'operadora_transporte_ps#new', as: :new
    get '/edit/:id', to: 'operadora_transporte_ps#edit', as: :edit
    post '/create/', to: 'operadora_transporte_ps#create', as: :create
    patch '/update/:id', to: 'operadora_transporte_ps#update', as: :update
    delete '/destroy/:id', to: 'operadora_transporte_ps#destroy', as: :destroy
    get '/show/:id', to: 'operadora_transporte_ps#show', as: :show
    get '/consultar/', to: 'operadora_transporte_ps#consultar', as: :consultar
    post 'ciudad_municipio', to: 'operadora_transporte_ps#ciudad_municipio', as: :ciudad_municipio
  end
  namespace :servicio do
    get '/index/consulta', to: 'servicio_operadora_cs#index_consulta', as: :index_consulta
    get '/index/', to: 'servicio_operadora_cs#index', as: :index
    get '/new/', to: 'servicio_operadora_cs#new', as: :new
    get '/edit/:id', to: 'servicio_operadora_cs#edit', as: :edit
    post '/create/', to: 'servicio_operadora_cs#create', as: :create
    patch '/update/:id', to: 'servicio_operadora_cs#update', as: :update
    delete '/destroy/:id', to: 'servicio_operadora_cs#destroy', as: :destroy
    get '/show/:id', to: 'servicio_operadora_cs#show', as: :show
    get '/show/consulta/:id', to: 'servicio_operadora_cs#show_consulta', as: :show_consulta
    post '/end/', to: 'servicio_operadora_cs#end_carga', as: :end_carga
    post '/set_codigo_rotp/', to: 'servicio_operadora_cs#set_codigo_rotp', as: :set_codigo_rotp
  end

  namespace :historico do
    get '/index', to: 'historico_solicitudes_aprobs#index', as: :index
    # get '/new/', to: 'historico_solicitudes_aprobs#new', as: :new
    get '/edit/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#edit', as: :edit
    post '/create/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#create', as: :create
    patch '/update/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#update', as: :update
    delete '/destroy/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#destroy', as: :destroy
    get '/show/:id', to: 'historico_solicitudes_aprobs#show',as: :show
    get '/consulta/final', to: 'historico_solicitudes_aprobs#consulta',as: :consulta
    get 'verificar/regreso', to: 'historico_solicitudes_aprobs#verificar_regreso', as: :verificar_regreso
    # get '/show/:id', to: 'historico_solicitudes_aprobs#show', as: :show
  end

  namespace :asegurador do
    get '/index/', to: 'aseguradoras#index', as: :index
    get '/edit/:id', to: 'aseguradoras#edit', as: :edit
    post '/create/', to: 'aseguradoras#create', as: :create
    patch '/update/:id', to: 'aseguradoras#update', as: :update
    delete '/destroy/:id', to: 'aseguradoras#destroy', as: :destroy
    post '/rif/', to: 'aseguradoras#rif_aseguradora', as: :rif_a
  end

  namespace :flota_d do
    get '/index/', to: 'flota#index', as: :index
    get '/new/', to: 'flota#new', as: :new
    get '/edit/:id', to: 'flota#edit', as: :edit
    post '/create/', to: 'flota#create', as: :create
    patch '/update/:id', to: 'flota#update', as: :update
    delete '/destroy/:id', to: 'flota#destroy', as: :destroy
    get '/show/:id', to: 'flota#show', as: :show
  end

  namespace :seguro do
    get '/index/', to: 'seguro_vehiculos#index', as: :index
    get '/new/', to: 'seguro_vehiculos#new', as: :new
    get '/edit/:id', to: 'seguro_vehiculos#edit', as: :edit
    post '/create/', to: 'seguro_vehiculos#create', as: :create
    patch '/update/:id', to: 'seguro_vehiculos#update', as: :update
    delete '/destroy/:id', to: 'seguro_vehiculos#destroy', as: :destroy
    get '/show/:id', to: 'seguro_vehiculos#show', as: :show
  end

  namespace :ruta_flota do
    get '/index/', to: 'ruta#index', as: :index
    get '/new/', to: 'ruta#new', as: :new
    get '/edit/:id', to: 'ruta#edit', as: :edit
    post '/create/', to: 'ruta#create', as: :create
    patch '/update/:id', to: 'ruta#update', as: :update
    delete '/destroy/:id', to: 'ruta#destroy', as: :destroy
    get '/show/:id', to: 'ruta#show', as: :show
    get '/new_taxi/', to: 'ruta#new_taxi', as: :new_taxi
    get '/edit_taxi/:id', to: 'ruta#edit_taxi', as: :edit_taxi
    patch '/update_taxi/:id', to: 'ruta#update_taxi', as: :update_taxi
    post '/create/taxi', to: 'ruta#create_taxi', as: :create_taxi
    get 'nueva/parada', to: 'ruta#nueva_parada', as: :nueva_parada
    post 'guardar/parada', to: 'ruta#guardar_parada', as: :guardar_parada
  end

  namespace :localizacion_select do
    post 'lista/municipios', to: 'busquedas#estado_municipios', as: 'estado_municipios'
    post 'lista/ciudades', to: 'busquedas#estado_ciudades', as: 'estado_ciudades'

app/controllers/estadistica_module/estadistica_controller.rb
module EstadisticaModule

  class EstadisticaController < ApplicationController
    before_filter :authenticate_session_user!
    def modalidad_estado_all
      @total = []
      @estadistica, @total[0], @total[1] = Estadistica.modalidad_estado
    end

    def modalidad_estado
      @total = []
      if params[:estado_id][:id].nil? || params[:estado_id][:id].blank?
        @error = true
        render :selector_ano_modalidad
      else
        @total[3] = Estado.find_by(id: params[:estado_id][:id]).nombre
        @estadistica, @total[0], @total[1] = Estadistica.modalidad_estado(params[:estado_id][:id])
      end
    end

    def selector_ano_modalidad #No quitar este metodo
    end

    def selector_parroquias #No quitar este metodo
    end

    def modalidad_parroquias
      @total = []
      if params[:municipio_id][:id].nil? || params[:municipio_id][:id].blank? ||  params[:municipio_id][:id] == "null"
        @error = true
        render :selector_parroquias
      else
        @total[3] = Municipio.find_by(id: params[:municipio_id][:id]).nombre
        @total[2] = ParroquiaV.where(municipio_id: params[:municipio_id][:id]).pluck(:nombre)
        @estadistica, @total[0], @total[1] = Estadistica.modalidad_estado(params[:estado_id][:id])
      end
    end

    def selector_ciudad #No quitar este metodo
    end

    def modalidad_ciudad
      @total = []
      if params[:estado_id][:id].nil? || params[:estado_id][:id].blank?
        @error = true
        render :selector_ciudad
      else
        @total[3] = Estado.find_by(id: params[:estado_id][:id]).nombre
        @total[2] = Ciudad.where(estado_id: params[:estado_id][:id]).pluck(:nombre)
        @estadistica, @total[0], @total[1] = Estadistica.modalidad_estado(params[:estado_id][:id])
      end
    end

    def modalidad_cupo_autorizado
      @total = []
      @estadistica, @total[0], @total[1] = Estadistica.modalidad_cupo_autorizado
    end

    def selector_ano_vencimiento_flota
    end

    def selector_ano_vencimiento_cps
    end

    def vencimiento_flota
      @total = []
      fecha = params[:date][:year].nil? || params[:date][:year] == "" ? Date.today.year : params[:date][:year]
      @estadistica, @total[0], @total[1], @total[2] = Estadistica.vencimiento_flota(fecha)
      @total[3] = fecha
    end

    def vencimiento_cps
      @total = []
      fecha = params[:date][:year].nil? || params[:date][:year] == "" ? Date.today.year : params[:date][:year]
      @estadistica, @total[0], @total[1], @total[2] = Estadistica.vencimiento_cps(fecha)
      @total[3] = fecha
    end


    def selector_proximas_vencer_flota
    end

    def proximas_vencer_flota
      @total = []
      @estadistica, @total[0], @total[1], @total[2] = Estadistica.proximas_vencer_flota(params[:meses].to_i)

    end
    def vistas_estados
      @estados, @modalidad, @estadisticas, @totales = Estadistica.calc_vistas_estados
    end

    def modalidad_tipo_unidad
      @total = []
      @total[1] = Estado.find_by(id: params[:estado_id][:id]).nombre
      if params[:estado_id][:id].nil? || params[:estado_id][:id].blank?
        @error = true
        render :selector_estados_tipo_unidad
      else
        @tipo, @modalidad, @estadistica = Estadistica.calc_vistas_tipo_unidad(params[:estado_id][:id])

      end
    end

    def vistas_parroquias
       if params[:municipio_id][:id].nil? || params[:municipio_id][:id].blank? ||  params[:municipio_id][:id] == "null"
        @error = true
        render :selector_parroquias
      else
        @municipio = Municipio.find_by(id: params[:municipio_id][:id]).nombre
        @parroquias, @modalidad, @totales, @estadistica = Estadistica.calc_vistas_mod_parroquias(params[:municipio_id][:id])
      end
    end

    def vistas_ciudad
      if params[:estado_id][:id].nil? || params[:estado_id][:id].blank?
        @error = true
        render :selector_ciudad
      else
        @estado = Estado.find_by(id: params[:estado_id][:id]).nombre
        @ciudad, @modalidad, @totales, @estadistica = Estadistica.vistas_mod_ciudad(params[:estado_id][:id])
      end
    end

    def selector_estados_tipo_unidad
    end

    def selector_meses_historicos
    end
    def nro_tramites_realizados_historicos
      @total = []
      mes = params[:date][:month].nil? || params[:date][:month] == "" ? Date.today.month : params[:date][:month]
      @total[1]= mes
      @certificacion, @estatus, @estadistica = Estadistica.calc_tramites_historicos(mes)
    end

    def form_igual_parada

    end

    def estadistica_igual_parada
      @parametros = Hash.new
      @parametros[:estado]      = params[:value][:id]
      @parametros[:tipo_parada] = ActiveRecord::Base.connection.quote(params[:value][:tipo_parada])
      @parametros[:parada]      = params[:parada_igual]
      consulta = EstadisticasSql.new
      connection = ActiveRecord::Base.connection
      @registros = connection.exec_query(consulta.igual_parada(@parametros[:estado],
                                                               @parametros[:tipo_parada],
                                                               @parametros[:parada]))
    end
  end
end

app/helpers/estadistica_helper.rb
module EstadisticaHelper

end

app/views/estadistica_module/estadistica/estadistica_igual_parada.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Administrador
    %ol.breadcrumb
      %li
        Otros
      %li.text-navy
        %b
          Operadora con igual parada
.wrapper.wrapper-content.animated.fadeInRight
  - if @registros.empty?
    .row
    .col-sm-12
      .wapper.wrapper-content.animated.fadeInDown
        .ibox
          .alert.alert-danger
            .ibox-content.text-center
              %h2
                %i.fa.fa-exclamation-triangle.yellow-warning
                %b
                  ¡ATENCIÓN!...
              %h3
                No posee Estadisticas para mostrar.
              %h4
                Esto se debe a que no existen datos consistentes que permitan un cálculo.
              %p.text-muted
                *Si usted cree que la operación que realiza debería arrojar estadísticas,
                comuníquese con los técnicos encargados del sistema.
  - else
    .col-sm-6.col-md-offset-3
      %table.table.table-striped.table-bordered.table-condensed
        %tbody
          - @registros.each do |row|
            %tr
              %td
                = row['servicio'].to_s.upcase
              %td
                = row['total']
  %br/
  .row
    .col-sm-4.col-sm-offset-4
      = form_for(:value, url: index_op_igual_parada_path, html: { class: 'form-horizontal m-t-md', id: 'form-vencimiento-mes-flota'}) do |f|
        .row
          = f.hidden_field :estado,value: @parametros[:estado]
          = f.hidden_field :tipo_parada,value: @parametros[:tipo_parada]
          = f.hidden_field :parada,value: @parametros[:parada]
          .col-sm-12
            .form-group
              .col-sm-4.col-md-offset-4
                = f.submit 'Listar Operadoras', class: 'btn btn-success', data: { disable_with: "Por favor espere..." }
  %br/
  .row
    .col-sm-4
      = link_to "Regresar", estadistica_module_form_igual_parada_path, class: 'btn btn-info'
    .col-sm-4

app/views/estadistica_module/estadistica/estado_tipo_parada.html.haml
%h1
  estado_tipo_parada

app/views/estadistica_module/estadistica/modalidad_ciudad.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Administrador
    %ol.breadcrumb
      %li
        Estadisticas de operadoras por modalidad de servicio
      %li.text-navy
        %b
          Por Ciudad


.wrapper.wrapper-content.animated.fadeInRight
  = render partial: 'capturar_error'
  - unless @estadistica.blank? || @estadistica == "false" || @estadistica.nil?
    .ibox-content
      .row
        .col-sm-12
          %h3
            Estadísticas por Ciudad del Estado:
            %b
              = @total[3]
          %br/
      .row
        .col-sm-12
          %table.table.table-striped.table-bordered.table-condensed
            %thead
              %tr
                %th
                  Ciudades
                - ServicioOperadoraC.modalidad_servicios.each do |mo, val|
                  %th
                    = val
            %tbody
              - @estadistica.each_with_index do |stat, index|
                %tr
                  %td
                    = @total[2][index]
                  - if stat.nil?
                    - (1..ServicioOperadoraC.modalidad_servicios.count).each do |a|
                      %td
                        %p
                          = "-"
                  - else
                    - stat.each do |s|
                      %td
                        = s
            %tfoot{style: "border: solid #1f90d8"}
              %tr
                %td
                  %b.text-navy
                    TOTAL
                - @total[0].each do |a|
                  %td
                    = a
  %br/
  .row
    .col-sm-4
      = link_to "Regresar", estadistica_module_selector_ciudad_path, class: 'btn btn-info'
    .col-sm-4
  %br/

app/views/estadistica_module/estadistica/proximas_vencer_flota.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Administrador
    %ol.breadcrumb
      %li
        Estadísticas de Flotas proximas a vencer
      %li.text-navy
        %b
          Todos los Estados
.wrapper.wrapper-content.animated.fadeInRight{style: "padding: 20px 10px 0px"}
  .ibox.float-e-margins
    .ibox-title
      %h5
        Menu de seleccion para listar las Operadoras
        %small Lista
      .ibox-tools
        %a.collapse-link
          %i.fa.fa-chevron-down
    = form_for(:value, url: index_op_fl_vencer_path, html: { class: 'form-horizontal m-t-md', id: 'form-vencimiento-mes-flota'}) do |f|
      .ibox-content{style: "display: none;"}
        .row
          .col-sm-12
            .form-group
              = label :estado, :estado, class: 'col-sm-4 control-label' do
                Estado de Ubicación para calcular las estadisticas:
                %span.fa.fa-asterisk.red
              .col-sm-8
                = collection_select  :value, :estado, Estado.order(:nombre), :id, :nombre,
                  {selected: false},
                  { class: "form-control", id: "estado_to_stad"}
            .form-group
              = f.label :cantidad_meses, class: 'col-sm-4 control-label' do
                Cantidad de meses:
                %span.fa.fa-asterisk.red
              .col-md-8
                = f.select :meses, options_for_select([1,2,3,4,5,6,7,8,9,10,11,12]),{},{class: "form-control"}
            .form-group
              .col-sm-4.col-md-offset-4
                = f.submit 'Listar', class: 'btn btn-success', data: { disable_with: "Por favor espere..." }

.wrapper.wrapper-content.animated.fadeInRight
  = render partial: 'capturar_error'
  - unless @estadistica.blank? || @estadistica == "false" || @estadistica.nil?
    .ibox-content
      %h3
        Estadisticas para:
        %b
          = " de #{@total[1][0]}" + " a " + "#{@total[1][(@total[1].length - 1)]}"
      .row
        .col-sm-12
          %table.table.table-striped.table-bordered.table-condensed
            %thead
              %tr
                %th
                  Estado
                - @total[1].each do |val|
                  %th
                    = val
            %tbody
              - @estadistica.each_with_index do |stat, index|
                %tr
                  %td
                    = @total[2][index]
                  - if stat.nil?
                    - (1..@total[1].length).each do |a|
                      %td
                        %p
                          = "-"
                  - else
                    - stat.each do |s|
                      %td
                        = s
            %tfoot{style: "border: solid #1f90d8"}
              %tr
                %td
                  %b.text-navy
                    TOTAL
                - @total[0].each do |a|
                  %td
                    = a
  .ibox-content
    .row
      .col-sm-4
        = link_to "Regresar", estadistica_module_selector_proximas_vencer_flota_path, class: 'btn btn-info'
      .col-sm-4

app/views/estadistica_module/estadistica/selector_ano_modalidad.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Administrador
    %ol.breadcrumb
      %li
        Estadísticas de operadoras por modalidad de servicio
      %li.text-navy
        %b
          Por Municipios


.wrapper.wrapper-content.animated.fadeInRight
  - if @error
    .ibox-content
      .alert.alert-danger.alert-dismissable.alerts-fix#error_explanation
        %h3
          Error de búsqueda para el cálculo de estadísticas
        %ul
          %li
            No puede realizarse la búsqueda si no ha seleccionado un estado
      %br/
  = form_for(:value, url: estadistica_module_modalidad_estado_path, html: { class: 'form-horizontal m-t-md'}) do |f|
    .ibox-content
      .row
        .col-sm-12
          .form-group
            = label :estado, :estado, class: 'col-sm-4 control-label' do
              Estado de Ubicación para calcular las estadisticas:
              %span.fa.fa-asterisk.red
            .col-sm-8
              = collection_select  :estado_id, :id, Estado.order(:nombre), :id, :nombre,
                {selected: false, include_blank: "Seleccione un Estado"},
                { class: "form-control", id: "estado_to_stad"}
      .row
        .col-md-12
          .ibox.float-e-margins
            .ibox-content
              .row
                .col-sm-4
                .col-sm-4
                  = f.submit 'Calcular Estadísticas', class: 'btn btn-success', data: { disable_with: "Por favor espere..." }

app/views/estadistica_module/estadistica/vencimiento_cps.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Administrador
    %ol.breadcrumb
      %li
        Estadísticas de vencimiento CPS en el año
      %li.text-navy
        %b
          Todos los Estados
.wrapper.wrapper-content.animated.fadeInRight{style: "padding: 20px 10px 0px"}
  .ibox.float-e-margins
    .ibox-title
      %h5
        Menu de seleccion para listar las Operadoras
        %small Lista
      .ibox-tools
        %a.collapse-link
          %i.fa.fa-chevron-down
    = form_for(:value, url: index_op_mes_cps_path, html: { class: 'form-horizontal m-t-md', id: 'form-vencimiento-mes-flota'}) do |f|
      .ibox-content{style: "display: none;"}
        .row
          .col-sm-12
            .form-group
              = label :estado, :estado, class: 'col-sm-4 control-label' do
                Estado de Ubicación para calcular las estadisticas:
                %span.fa.fa-asterisk.red
              .col-sm-8
                = collection_select  :estado, :id, Estado.order(:nombre), :id, :nombre,
                  {selected: false},
                  { class: "form-control", id: "estado_to_stad"}
            .form-group
              = f.label :modalidad_servicio, class: 'col-sm-4 control-label' do
                Mes de Vencimiento:
                %span.fa.fa-asterisk.red
              .col-md-8
                = select_month(Date.today,{}, {class: "form-control"})
            .form-group
              = label :estado, :estado, class: 'col-sm-4 control-label' do
                Año de Vencimiento de la Flota para calcular:
                %span.fa.fa-asterisk.red
              .col-sm-8
                = select_year(Date.today, {start_year: Date.today.year.to_i - 60, end_year: Date.today.year.to_i + 10}, {class: "form-control"})
            .form-group
              .col-sm-4.col-md-offset-4
                = f.submit 'Listar', class: 'btn btn-success', data: { disable_with: "Por favor espere..." }
.wrapper.wrapper-content.animated.fadeInRight
  = render partial: 'capturar_error'
  - unless @estadistica.blank? || @estadistica == "false" || @estadistica.nil?
    .ibox-content
      %h3
        Estadisticas para el año:
        %b
          = @total[3]
      .row
        .col-sm-12
          %table.table.table-striped.table-bordered.table-condensed
            %thead
              %tr
                %th
                  Estado
                - @total[1].each do |val|
                  %th
                    = val
            %tbody
              - @estadistica.each_with_index do |stat, index|
                %tr
                  %td
                    = @total[2][index]
                  - if stat.nil?
                    - (1..12).each do |a|
                      %td
                        %p
                          = "-"
                  - else
                    - stat.each do |s|
                      %td
                        = s
            %tfoot{style: "border: solid #1f90d8"}
              %tr
                %td
                  %b.text-navy
                    TOTAL
                - @total[0].each do |a|
                  %td
                    = a
  .ibox-content
    .row
      .col-sm-4
        = link_to "Regresar", estadistica_module_selector_ano_vencimiento_cps_path, class: 'btn btn-info'
      .col-sm-4