config/routes.rb
# -*- encoding : utf-8 -*-
Rails.application.routes.draw do
  root :to =>'static_pages#home'
  get '/registrado',to: 'static_pages#later_register', as: :registrado

  namespace :admin do
    resources :modalidad_servicios
  end
  namespace :estadistica_module do
    get '/modalidad/todos/estados', to: 'estadistica#modalidad_estado_all', as: :modalidad_estado_all
    get '/modalidad/cupo/estados', to: 'estadistica#modalidad_cupo_autorizado', as: :modalidad_cupo_autorizado
    post '/modalidad/estado', to: 'estadistica#modalidad_estado', as: :modalidad_estado
    post '/modalidad/parroquias', to: 'estadistica#modalidad_parroquias', as: :modalidad_parroquias
    post '/modalidad/ciudad', to: 'estadistica#modalidad_ciudad', as: :modalidad_ciudad
    get '/modalidad/estado/seleccion', to: 'estadistica#selector_ano_modalidad', as: :selector_ano_modalidad
    get '/modalidad/parroquias/seleccion', to: 'estadistica#selector_parroquias', as: :selector_parroquias
    get '/modalidad/ciudad/seleccion', to: 'estadistica#selector_ciudad', as: :selector_ciudad
    post '/unidades/todos/estado/', to: 'estadistica#vencimiento_flota', as: :vencimiento_flota
    get '/vencimiento/ano/seleccion/flota',to: 'estadistica#selector_ano_vencimiento_flota', as: :selector_ano_vencimiento_flota
    get '/vencimiento/ano/seleccion/cps',to: 'estadistica#selector_ano_vencimiento_cps', as: :selector_ano_vencimiento_cps
    post '/vencimiento/ano/cps', to: 'estadistica#vencimiento_cps', as: :vencimiento_cps
    get '/vistas/estados/modalidad', to: 'estadistica#vistas_estados', as: :vistas_estados
    get '/selector/proximas/vencer/flota/', to: 'estadistica#selector_proximas_vencer_flota', as: :selector_proximas_vencer_flota
    post '/proximas/vencer/flota/', to: 'estadistica#proximas_vencer_flota', as: :proximas_vencer_flota
    get '/modalidad/estados/tipounidad/', to: 'estadistica#selector_estados_tipo_unidad', as: :selector_estados_tipo
    post '/modalidad/tipounidad', to: 'estadistica#modalidad_tipo_unidad', as: :modalidad_tipo_unidad
    get '/form/igual/parada/', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/estadistica/igual/parada/', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    get '/meses/seleccion/historicos', to: 'estadistica#selector_meses_historicos', as: :selector_meses_historicos
    post '/tramites/historicos', to: 'estadistica#nro_tramites_realizados_historicos', as: :tramites_historicos
    post '/vistas/parroquias', to: 'estadistica#vistas_parroquias', as: :vistas_parroquias
    post '/vistas/ciudad', to: 'estadistica#vistas_ciudad', as: :vistas_ciudad
  end

  scope module: 'listas' do
    post '/operadoras/listadas/rutas', to: 'listado#listar_por_rutas', as: :listar_por_rutas
    get '/creador/rutas/buscar', to: 'listado#creador_rutas_buscar', as: :creador_rutas
    get '/operadoras/index/', to: 'listado#index_operadora', as: :index_operadora
    get '/operadora/igual/parada', to: 'estadistica#form_igual_parada', as: :form_igual_parada
    post '/resultado/igual/parada', to: 'estadistica#estadistica_igual_parada', as: :estadistica_igual_parada
    post '/operadoras/est/mod', to: 'listado#index_operadora_est_mod', as: :index_est_mod
    post '/operadoras/vencimiento/mes', to: 'listado#index_operadora_mes_ven', as: :index_op_mes_venc
    post '/operadoras/tipounidadvehicular', to: 'listado#index_operadora_tipo_unidad', as: :index_tipo_unidad
    post '/operadoras/vencimiento/mes/cps', to: 'listado#index_op_mes_cps', as: :index_op_mes_cps
    post '/operadoras/igual/parada', to: 'listado#index_op_igual_par', as: :index_op_igual_parada
    post '/operadoras/flota/vencer', to: 'listado#index_ope_flo_venc', as: :index_op_fl_vencer
  end

  namespace :horario_d do
    # get '/index/', to: 'horarios#index', as: :index
    get '/index/', to: 'horarios_dinamico#index', as: :index
    get '/new/', to: 'horarios#new', as: :new
    get '/edit/:id', to: 'horarios#edit', as: :edit
    post '/create/', to: 'horarios#create', as: :create
    patch '/update/:id', to: 'horarios#update', as: :update
    delete '/destroy/:id', to: 'horarios#destroy', as: :destroy
    get '/show/:id', to: 'horarios#show', as: :show
    get 'consultar/show/:id', to: 'horarios#consultar_show', as: :consultar
    post '/horarios/guardar/', to: 'horarios_dinamico#crear_horario', as: :crear_horario
    get '/horarios/eliminar/horario/:id', to: 'horarios_dinamico#eliminar_horario', as: :eliminar_horario_lista
  end

  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena', to: 'session_users/sessions#edit_password'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    post 'reestablecer_password',
                    to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
      { :registrations => 'session_users/registrations',
        :sessions =>'session_users/sessions',
        :passwords => 'session_users/passwords'}

  namespace :operadora do
    get '/index/', to: 'operadora_transporte_ps#index', as: :index
    get '/new/', to: 'operadora_transporte_ps#new', as: :new
    get '/edit/:id', to: 'operadora_transporte_ps#edit', as: :edit
    post '/create/', to: 'operadora_transporte_ps#create', as: :create
    patch '/update/:id', to: 'operadora_transporte_ps#update', as: :update
    delete '/destroy/:id', to: 'operadora_transporte_ps#destroy', as: :destroy
    get '/show/:id', to: 'operadora_transporte_ps#show', as: :show
    get '/consultar/', to: 'operadora_transporte_ps#consultar', as: :consultar
    post 'ciudad_municipio', to: 'operadora_transporte_ps#ciudad_municipio', as: :ciudad_municipio
  end
  namespace :servicio do
    get '/index/consulta', to: 'servicio_operadora_cs#index_consulta', as: :index_consulta
    get '/index/', to: 'servicio_operadora_cs#index', as: :index
    get '/new/', to: 'servicio_operadora_cs#new', as: :new
    get '/edit/:id', to: 'servicio_operadora_cs#edit', as: :edit
    post '/create/', to: 'servicio_operadora_cs#create', as: :create
    patch '/update/:id', to: 'servicio_operadora_cs#update', as: :update
    delete '/destroy/:id', to: 'servicio_operadora_cs#destroy', as: :destroy
    get '/show/:id', to: 'servicio_operadora_cs#show', as: :show
    get '/show/consulta/:id', to: 'servicio_operadora_cs#show_consulta', as: :show_consulta
    post '/end/', to: 'servicio_operadora_cs#end_carga', as: :end_carga
    post '/set_codigo_rotp/', to: 'servicio_operadora_cs#set_codigo_rotp', as: :set_codigo_rotp
  end

  namespace :historico do
    get '/index', to: 'historico_solicitudes_aprobs#index', as: :index
    # get '/new/', to: 'historico_solicitudes_aprobs#new', as: :new
    get '/edit/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#edit', as: :edit
    post '/create/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#create', as: :create
    patch '/update/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#update', as: :update
    delete '/destroy/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#destroy', as: :destroy
    get '/show/:id', to: 'historico_solicitudes_aprobs#show',as: :show
    get '/consulta/final', to: 'historico_solicitudes_aprobs#consulta',as: :consulta
    get 'verificar/regreso', to: 'historico_solicitudes_aprobs#verificar_regreso', as: :verificar_regreso
    # get '/show/:id', to: 'historico_solicitudes_aprobs#show', as: :show
  end

  namespace :asegurador do
    get '/index/', to: 'aseguradoras#index', as: :index
    get '/edit/:id', to: 'aseguradoras#edit', as: :edit
    post '/create/', to: 'aseguradoras#create', as: :create
    patch '/update/:id', to: 'aseguradoras#update', as: :update
    delete '/destroy/:id', to: 'aseguradoras#destroy', as: :destroy
    post '/rif/', to: 'aseguradoras#rif_aseguradora', as: :rif_a
  end

  namespace :flota_d do
    get '/index/', to: 'flota#index', as: :index
    get '/new/', to: 'flota#new', as: :new
    get '/edit/:id', to: 'flota#edit', as: :edit
    post '/create/', to: 'flota#create', as: :create
    patch '/update/:id', to: 'flota#update', as: :update
    delete '/destroy/:id', to: 'flota#destroy', as: :destroy
    get '/show/:id', to: 'flota#show', as: :show
  end

  namespace :seguro do
    get '/index/', to: 'seguro_vehiculos#index', as: :index
    get '/new/', to: 'seguro_vehiculos#new', as: :new
    get '/edit/:id', to: 'seguro_vehiculos#edit', as: :edit
    post '/create/', to: 'seguro_vehiculos#create', as: :create
    patch '/update/:id', to: 'seguro_vehiculos#update', as: :update
    delete '/destroy/:id', to: 'seguro_vehiculos#destroy', as: :destroy
    get '/show/:id', to: 'seguro_vehiculos#show', as: :show
  end

  namespace :ruta_flota do
    get '/index/', to: 'ruta#index', as: :index
    get '/new/', to: 'ruta#new', as: :new
    get '/edit/:id', to: 'ruta#edit', as: :edit
    post '/create/', to: 'ruta#create', as: :create
    patch '/update/:id', to: 'ruta#update', as: :update
    delete '/destroy/:id', to: 'ruta#destroy', as: :destroy
    get '/show/:id', to: 'ruta#show', as: :show
    get '/new_taxi/', to: 'ruta#new_taxi', as: :new_taxi
    get '/edit_taxi/:id', to: 'ruta#edit_taxi', as: :edit_taxi
    patch '/update_taxi/:id', to: 'ruta#update_taxi', as: :update_taxi
    post '/create/taxi', to: 'ruta#create_taxi', as: :create_taxi
    get 'nueva/parada', to: 'ruta#nueva_parada', as: :nueva_parada
    post 'guardar/parada', to: 'ruta#guardar_parada', as: :guardar_parada
  end

  namespace :localizacion_select do
    post 'lista/municipios', to: 'busquedas#estado_municipios', as: 'estado_municipios'
    post 'lista/ciudades', to: 'busquedas#estado_ciudades', as: 'estado_ciudades'

app/models/session_user.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: session_users
#
#  id                     :integer          not null, primary key
#  email                  :string(50)       default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  created_at             :datetime
#  updated_at             :datetime
#  usuario_sput_id        :integer          not null
#

class SessionUser < ActiveRecord::Base
  include RegexHelper
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :usuario
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  #asociaciones
  belongs_to :usuario_sput
  accepts_nested_attributes_for :usuario_sput

  #validates
  validates :usuario_sput_id, :uniqueness => true
  validates :email,:length => {  maximum: 50,
                                 message:
                                     'Email debe contener máximo 50 caracteres'
                  }
  validates_presence_of :email_confirmation , on: :create
  validates_format_of :email, with: VALID_EMAIL_REGEX
  validates_confirmation_of :email,
                            message: 'Correo y su confirmación no coincide'
  validates :usuario_sput_id,
            uniqueness: {message: 'Error del sistema, no duplicados de registro'}
  validate :correos_diferentes

  def correos_diferentes
    if self.usuario_sput.correo_alterno == self.email
      errors.add(:email, "Debe usar un correo alterno diferente al email principal")
    end
  end

  #metodos consulta
  def operadoras
    self.usuario.operadora_transporte_ps
  end

  def servicios #no funciona aun
    self.operadoras.servicio_operadora_cs
  end

  def servicio_flota(servicio)
    self.operadoras.servicio_operadora_cs.where(id: servicio).last  end


end

app/controllers/session_users/passwords_controller.rb
# -*- encoding : utf-8 -*-
class SessionUsers::PasswordsController < Devise::PasswordsController
  before_action :configure_params, only: [:permit_reset_password,:create]

  def new
    super
  end

  def permit_reset_password

    self.resource = resource_class.new
    @email = params[:session_user][:email]

    if @email.blank?
      resource.errors[:base] << 'Correo no puede estar en blanco'
      render 'new'
      return
    end

    @session_user_db  = SessionUser.find_by(email: @email)

    if @session_user_db.nil?
      resource.errors[:base] << 'Correo no registrado'
      render 'new'
      return
    end

    @pregunta = @session_user_db.usuario_sput.pregunta_secreta
  end

  def create
    self.resource = resource_class.new
    @email = params[:session_user][:email]
    @respuesta =espacios_blancos_l_r(params[:session_user][:respuesta])

    if @email.blank? or @respuesta.blank?
      resource.errors[:base] << 'Respuesta no puede estar en blanco'
      render 'new'
      return
    end

    @session_user_db  = SessionUser.find_by(email: @email)

    if @session_user_db.nil?
      resource.errors[:base] << 'Correo no registrado'
      render 'new'
      return
    end

    @respuesta_bd = espacios_blancos_l_r(@session_user_db.usuario_sput.respuesta)

    unless @respuesta_bd.casecmp(@respuesta) == 0
      @pregunta = @session_user_db.usuario_sput.pregunta_secreta
      resource.errors[:base] << 'Respuesta incorrecta intente de nuevo'
      render 'permit_reset_password'
      return
    end
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  private
  def configure_params
    params.require(:session_user).permit(:email, :respuesta)
  end

end

app/controllers/session_users/sessions_controller.rb
class SessionUsers::SessionsController < Devise::SessionsController
  before_filter :authenticate_session_user!, only: [:edit_password,
                                                    :update_password]
# GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    # super
    self.resource = warden.authenticate!(auth_options)
    sign_in(resource_name, resource)
    yield resource if block_given?
    after_sign_in_path_modified(resource)
    # fin super

    if resource.usuario.temporal?
      flash[:warning]= 'Debes cambiar tu clave para activar tu cuenta'
      redirect_to cambio_contrasena_path
    else
      set_flash_message(:notice, :signed_in) if is_flashing_format?
      redirect_to root_path
    end

  end

  # DELETE /resource/sign_out
  def destroy
    super
  end


  #metodos para modificar password si usuario esta en estado temporal
  def edit_password
    @session_user = current_session_user
  end

  def update_password
    @session_user = SessionUser.find(current_session_user.id)
    if @session_user.update(configure_sign_in_params)
      # Sign in the user by passing validation in case their password changed
      sign_in @session_user, :bypass => true
      @session_user.usuario.autorizado!
      redirect_back_or root_path
    else
      render 'session_users/sessions/edit_password'
    end
  end

  private

  def after_sign_in_path_modified(resource_or_scope)
    stored_location_for(resource_or_scope)
  end

  # You can put the params you want to permit in the empty array.
  def configure_sign_in_params
    params.require(:session_user).permit( :password, :password_confirmation)
  end
end

app/helpers/session_users_helper.rb
# -*- encoding : utf-8 -*-
module SessionUsersHelper
  def autorized_user
    unless current_session_user.usuario.autorizado?
      store_location
      flash[:danger]= 'Debes cambiar tu clave para activar tu cuenta'
      redirect_to cambio_contrasena_path
    end
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_autorized_url] || default)
    session.delete(:forwarding_autorized_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_autorized_url] = request.url if request.get?
  end

  def devise_error_messages_modified!

    messages = resource.errors.map { |name,msg| content_tag(:li,
                                                            msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h2>#{sentence}</h2>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/views/session_users/shared/_form_registro.html.haml
-if @ciudadano.nil?
  %h4{class: 'cedula-fail'}
    No se encontro nínguna persona con esa combinación de cédula y  fecha de nacimiento
-else
  %div
    = form_for(resource, as: resource_name, url: registration_path(resource_name),
     html: {class:'form-horizontal', id: 'registro-usuario-form'}) do |f|
      - if !devise_error_messages!.empty?
        .alert.alert-danger
          = devise_error_messages!
      .form-group
        = f.label 'Correo electrónico:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = f.email_field :email, placeholder: 'Correo electrónico',
          class: 'form-control', autofocus: true,
          :required => 'required'
      .form-group
        = f.label 'Confirmar correo electrónico:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = text_field_tag :email_confirmation, nil,
          :placeholder =>"Confirma el correo",:required => 'required', :class => 'form-control col-lg-10'
      .form-group
        = f.label :email_alterno,'Correo Alterno:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = text_field_tag :email_alterno, nil,:placeholder =>'Correo Alterno',:required => 'required', :class => 'form-control col-lg-10'
      .form-group
        = f.label :pregunta_secreta,'Pregunta Secreta:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = text_field_tag :pregunta_secreta, nil,
          :placeholder =>'Pregunta secreta',:required => 'required',
          :class => 'form-control col-lg-10'
      .form-group
        = f.label :respuesta_secreta,'Respuesta Secreta:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = text_field_tag :respuesta_secreta, nil,
          :placeholder =>'Respuesta Secreta',:required => 'required',
          :class => 'form-control col-lg-10'
      .form-group
        = f.label :cargo,'Cargo:*',
        class: 'col-lg-6 control-label',style:'text-align: left'
        .col-lg-6
          = text_field_tag :cargo, nil,
          :placeholder =>'Cargo',:required => 'required',
          :class => 'form-control col-lg-10'
      -#.form-group
      -#  = f.label 'Contraseña:*', class: 'col-lg-6 control-label',
      -#  style:'text-align: left'
      -#  .col-lg-6
      -#    = f.password_field :password, placeholder: 'Contraseña',class: 'form-control', autofocus: true, autocomplete: "off", required: 'required'
      -#.form-group
      -#  =f.label 'Confirmar Contraseña:*', class: 'col-lg-6 control-label',
      -#  style:'text-align: left'
      -#  .col-lg-6
      -#    = f.password_field :password_confirmation, placeholder: 'Confirma tu Contraseña',class: 'form-control', autofocus: true, autocomplete: "off", required: 'required'
      .form-group
        = f.label 'Código de Verificación', class: ' control-label',
        style:'text-align: left'
        = recaptcha_tags :display => { :theme => "clean" }, :ajax => true, :public_key => ENV['RECAPTCHA_PUBLIC_KEY']
      -#.form-group.col-md-offset-1
      -#  .checkbox.i-checks
      -#    = check_box_tag :terminos, class: 'icheck'
      -#    Acepto los términos y condiciones

      %br/
      = f.submit "Registrate con Nosotros", class:"btn btn-success btn-block"
      - if controller_name != 'sessions'
        %br/
        %br/
        %p.text-muted.text-center
          %small Ya eres un usuario registrado?
        = link_to "Iniciar Sesión", new_session_path(resource_name), class: 'btn btn-default btn-block'
      %br/
      %br/

app/views/session_users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/session_users/shared/_subir_acta_socios.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @operadora_transporte_p.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.acta_socios.blank? ? '' : f.object.acta_socios.file.filename) %>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :acta_socios %>
  </span>
</div>

app/views/session_users/shared/_subir_cedula.html.erb
<div class="fileinput fileinput-new" data-provides="fileinput">
  <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
  <div>
    <span class="btn btn-default btn-file">
      <span class="fileinput-new">Copia Digital de la Cédula</span>
      <span class="fileinput-exists">Cambiar Copia Digital</span>
      <%= u.file_field :cedula_imagen,
                       :required => 'required' %>
    </span>
   </div>
</div>

app/views/session_users/shared/_subir_cooperativa.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @operadora_transporte_p.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.documento_cooperativa.blank? ? '' : f.object.documento_cooperativa.file.filename)%>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :documento_cooperativa %>
  </span>
</div>

app/views/session_users/shared/_subir_cps.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @servicio_operadora_c.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.cps.blank? ? '' : f.object.cps.file.filename) %>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :cps %>
  </span>
</div>

app/views/session_users/shared/_subir_documento.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @operadora_transporte_p.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.documento_acreditacion.blank? ? '' : f.object.documento_acreditacion.file.filename)%>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :documento_acreditacion %>
  </span>
</div>

app/views/session_users/shared/_subir_documento_historico.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @historico_solicitudes_aprob.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.documento_historico.blank? ? '' : f.object.documento_historico.file.filename) %>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :documento_historico %>
  </span>
</div>

app/views/session_users/shared/_subir_dt.html.erb
<div class="fileinput fileinput-new input-group" data-provides="fileinput">
  <div class="form-control" data-trigger="fileinput">
    <i class="fa fa-upload fileinput-exists"></i>
    <span class="fileinput-filename">
      <% unless @servicio_operadora_c.errors.any? %>
        <%= (action_name == 'new') ? '' : (f.object.dt.blank? ? '' : f.object.dt.file.filename) %>
      <% end %>
    </span>
  </div>
  <span class="input-group-addon btn btn-default btn-file">
    <span class="fileinput-new">Seleccionar Documento Digital</span>
    <span class="fileinput-exists">Cambiar Documento Digital</span>
    <%= f.file_field :dt %>
  </span>
</div>