config/routes.rb
    post '/operadoras/igual/parada', to: 'listado#index_op_igual_par', as: :index_op_igual_parada
    post '/operadoras/flota/vencer', to: 'listado#index_ope_flo_venc', as: :index_op_fl_vencer
  end

  namespace :horario_d do
    # get '/index/', to: 'horarios#index', as: :index
    get '/index/', to: 'horarios_dinamico#index', as: :index
    get '/new/', to: 'horarios#new', as: :new
    get '/edit/:id', to: 'horarios#edit', as: :edit
    post '/create/', to: 'horarios#create', as: :create
    patch '/update/:id', to: 'horarios#update', as: :update
    delete '/destroy/:id', to: 'horarios#destroy', as: :destroy
    get '/show/:id', to: 'horarios#show', as: :show
    get 'consultar/show/:id', to: 'horarios#consultar_show', as: :consultar
    post '/horarios/guardar/', to: 'horarios_dinamico#crear_horario', as: :crear_horario
    get '/horarios/eliminar/horario/:id', to: 'horarios_dinamico#eliminar_horario', as: :eliminar_horario_lista
  end

  devise_scope :session_user do
    get 'iniciar_sesion', to: 'devise/sessions#new'
    get 'registro', to: 'session_users/registrations#nuevo_registro'
    get 'cambio_contrasena', to: 'session_users/sessions#edit_password'
    patch 'actualizar_contrasena', to: 'session_users/sessions#update_password'
    get 'recuperar_contrasena', to: 'session_users/passwords#new'
    post 'reestablecer_password',
                    to:'session_users/passwords#permit_reset_password'
    delete 'cerrar_sesion', to: 'devise/sessions#destroy'
  end

  devise_for :session_users ,  :controllers =>
      { :registrations => 'session_users/registrations',
        :sessions =>'session_users/sessions',
        :passwords => 'session_users/passwords'}

  namespace :operadora do
    get '/index/', to: 'operadora_transporte_ps#index', as: :index
    get '/new/', to: 'operadora_transporte_ps#new', as: :new
    get '/edit/:id', to: 'operadora_transporte_ps#edit', as: :edit
    post '/create/', to: 'operadora_transporte_ps#create', as: :create
    patch '/update/:id', to: 'operadora_transporte_ps#update', as: :update
    delete '/destroy/:id', to: 'operadora_transporte_ps#destroy', as: :destroy
    get '/show/:id', to: 'operadora_transporte_ps#show', as: :show
    get '/consultar/', to: 'operadora_transporte_ps#consultar', as: :consultar
    post 'ciudad_municipio', to: 'operadora_transporte_ps#ciudad_municipio', as: :ciudad_municipio
  end
  namespace :servicio do
    get '/index/consulta', to: 'servicio_operadora_cs#index_consulta', as: :index_consulta
    get '/index/', to: 'servicio_operadora_cs#index', as: :index
    get '/new/', to: 'servicio_operadora_cs#new', as: :new
    get '/edit/:id', to: 'servicio_operadora_cs#edit', as: :edit
    post '/create/', to: 'servicio_operadora_cs#create', as: :create
    patch '/update/:id', to: 'servicio_operadora_cs#update', as: :update
    delete '/destroy/:id', to: 'servicio_operadora_cs#destroy', as: :destroy
    get '/show/:id', to: 'servicio_operadora_cs#show', as: :show
    get '/show/consulta/:id', to: 'servicio_operadora_cs#show_consulta', as: :show_consulta
    post '/end/', to: 'servicio_operadora_cs#end_carga', as: :end_carga
    post '/set_codigo_rotp/', to: 'servicio_operadora_cs#set_codigo_rotp', as: :set_codigo_rotp
  end

  namespace :historico do
    get '/index', to: 'historico_solicitudes_aprobs#index', as: :index
    # get '/new/', to: 'historico_solicitudes_aprobs#new', as: :new
    get '/edit/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#edit', as: :edit
    post '/create/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#create', as: :create
    patch '/update/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#update', as: :update
    delete '/destroy/:id_hist/:id/:id_from/:id_servicio', to: 'historico_solicitudes_aprobs#destroy', as: :destroy
    get '/show/:id', to: 'historico_solicitudes_aprobs#show',as: :show
    get '/consulta/final', to: 'historico_solicitudes_aprobs#consulta',as: :consulta
    get 'verificar/regreso', to: 'historico_solicitudes_aprobs#verificar_regreso', as: :verificar_regreso
    # get '/show/:id', to: 'historico_solicitudes_aprobs#show', as: :show
  end

  namespace :asegurador do
    get '/index/', to: 'aseguradoras#index', as: :index
    get '/edit/:id', to: 'aseguradoras#edit', as: :edit
    post '/create/', to: 'aseguradoras#create', as: :create
    patch '/update/:id', to: 'aseguradoras#update', as: :update
    delete '/destroy/:id', to: 'aseguradoras#destroy', as: :destroy
    post '/rif/', to: 'aseguradoras#rif_aseguradora', as: :rif_a
  end

  namespace :flota_d do
    get '/index/', to: 'flota#index', as: :index
    get '/new/', to: 'flota#new', as: :new
    get '/edit/:id', to: 'flota#edit', as: :edit
    post '/create/', to: 'flota#create', as: :create
    patch '/update/:id', to: 'flota#update', as: :update
    delete '/destroy/:id', to: 'flota#destroy', as: :destroy
    get '/show/:id', to: 'flota#show', as: :show
  end

  namespace :seguro do
    get '/index/', to: 'seguro_vehiculos#index', as: :index
    get '/new/', to: 'seguro_vehiculos#new', as: :new
    get '/edit/:id', to: 'seguro_vehiculos#edit', as: :edit
    post '/create/', to: 'seguro_vehiculos#create', as: :create
    patch '/update/:id', to: 'seguro_vehiculos#update', as: :update
    delete '/destroy/:id', to: 'seguro_vehiculos#destroy', as: :destroy
    get '/show/:id', to: 'seguro_vehiculos#show', as: :show
  end

  namespace :ruta_flota do
    get '/index/', to: 'ruta#index', as: :index
    get '/new/', to: 'ruta#new', as: :new
    get '/edit/:id', to: 'ruta#edit', as: :edit
    post '/create/', to: 'ruta#create', as: :create
    patch '/update/:id', to: 'ruta#update', as: :update
    delete '/destroy/:id', to: 'ruta#destroy', as: :destroy
    get '/show/:id', to: 'ruta#show', as: :show
    get '/new_taxi/', to: 'ruta#new_taxi', as: :new_taxi
    get '/edit_taxi/:id', to: 'ruta#edit_taxi', as: :edit_taxi
    patch '/update_taxi/:id', to: 'ruta#update_taxi', as: :update_taxi
    post '/create/taxi', to: 'ruta#create_taxi', as: :create_taxi
    get 'nueva/parada', to: 'ruta#nueva_parada', as: :nueva_parada
    post 'guardar/parada', to: 'ruta#guardar_parada', as: :guardar_parada
  end

  namespace :localizacion_select do
    post 'lista/municipios', to: 'busquedas#estado_municipios', as: 'estado_municipios'
    post 'lista/ciudades', to: 'busquedas#estado_ciudades', as: 'estado_ciudades'
    post 'lista/parroquias', to: 'busquedas#municipio_parroquias', as: 'municipio_parroquias'
    post 'lista/paradas', to: 'busquedas#parroquia_paradas', as: 'parroquia_paradas'
    post 'lista/estado/paradas', to: 'busquedas#estado_tipo_paradas', as: 'estado_tipo_paradas'
  end

  namespace :paradas do
    resources :adm_paradas
    get '/index/', to: 'toques_dinamico#index', as: :index
    # get '/new/', to: 'toques#new', as: :new
    get '/editar/:id_toque', to: 'toques_dinamico#editar', as: :editar
    post '/crear/', to: 'toques_dinamico#crear', as: :crear
    patch '/actualizar/:id_toque', to: 'toques_dinamico#actualizar', as: :actualizar
    get '/eliminar/:id_toque', to: 'toques_dinamico#eliminar', as: :eliminar
    get '/show/:id', to: 'toques_dinamico#show', as: :show
    get 'nueva/parada', to: 'toques_dinamico#nueva_parada', as: :toque_nueva_parada
    post 'guardar/parada', to: 'toques_dinamico#guardar_parada', as: :toque_guardar_parada
    get 'verificar/destino', to: 'toques_dinamico#verificar_destino_ruta', as: :verificar_cierre_toque

    get '/index/ubicacion/parada', to: 'paradas#index', as: :index_ubicacion
    get '/new/ubicacion/parada', to: 'paradas#new', as: :new_ubicacion
    post '/new_by_post/ubicacion/parada', to: 'paradas#new_by_post', as: :new_by_post_ubicacion
    get '/edit/:id/ubicacion/parada', to: 'paradas#edit', as: :edit_ubicacion
    post '/buscar/ubicacion/parada', to: 'paradas#buscar', as: :buscar_ubicacion
    post '/create/ubicacion/parada', to: 'paradas#create', as: :create_ubicacion
    post '/create/ubicacion/parada', to: 'paradas#create_ubicacion', as: :create_ubicacion_admin
    patch '/update/:id/ubicacion/parada', to: 'paradas#update', as: :update_ubicacion
    delete '/destroy/:id/ubicacion/parada', to: 'paradas#destroy', as: :destroy_ubicacion
    get '/show/:id/ubicacion/parada', to: 'paradas#show', as: :show_ubicacion

    post '/cookie/constructor/', to: 'paradas#cookie_contructor', as: :cookie_constructor
    get '/redirect/', to: 'paradas#redirect_parada', as: :redirect_parada
    get '/ruta_flota_new_path/full/', to: 'paradas#redirect_ruta_flota_new', as: :ruta_flota_redirect_new

    get '/error/parada', to: 'paradas#error_parada_ubicacion',as: :error_parada_ubicacion
  end

  namespace :dynamic_select do
    get ':estado_id/ciudades', to: 'ciudades#index', as: 'ciudades'
    get ':estado_id/municipios', to: 'municipios#index', as: 'municipios'
    get ':municipio_id/paradas', to: 'paradas#index', as: 'paradas'
    get ':parroquia_id/paradas/p/', to: 'paradas#index_parroquia', as: 'paradas_parroquia'
    get ':municipio_id/parroquias', to: 'parroquia_vs#index', as: 'parroquia_vs'
    post 'form_igual_parada/estado', to: 'paradas#estado_tipo_parada'

    post '/paradas/', to: 'paradas#parroquia_index', as: 'parroquia_index'
    post '/paradas/estado', to: 'paradas#estado_terminal_index', as: 'parroquia_estado_index'
  end

  #nested resources para seguro RCV
  resources :flota ,controller: 'flota_d/flota', only: :create  do
    resource :seguro_vehiculos , controller: 'seguro/seguro_vehiculos',
             only: [:create,:update]
  end

  #nested resources para crear vehiculos para una flota
  resources :flotas, controller: 'flota_d/flota' do
    resources :vehiculos, controller:  'vehiculos/vehiculos'
  end
  get 'vehiculo/arrendatario', to: 'vehiculos/vehiculos#tiene_arrendatario', as: :vehiculo_arrendatario
  post 'vehiculos/buscar_vehiculo', to: 'vehiculos/vehiculos#buscar_vehiculo'

app/models/vehiculo.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: vehiculos
#
#  id                         :integer          not null, primary key
#  placa                      :string(255)
#  s_carroceria               :string(255)
#  ano                        :string(255)
#  marca                      :string(255)
#  modelo                     :string(255)
#  color                      :string(255)
#  capacidad                  :integer
#  puesto                     :integer          default(0), not null
#  serial_motor               :string(255)
#  tipo_vehiculo              :string(255)
#  propietario                :string(255)
#  identificacion_propietario :string(255)
#  uso                        :string(255)      not null
#  tipo_unidad                :string(255)
#  status                     :boolean
#  flota_id                   :integer
#  created_at                 :datetime
#  updated_at                 :datetime
#

class Vehiculo < ActiveRecord::Base
  belongs_to :flota
  has_one :seguro_vehiculo, dependent: :destroy
  has_one :contrato_arrendamiento, dependent: :destroy
  accepts_nested_attributes_for :seguro_vehiculo
  accepts_nested_attributes_for :contrato_arrendamiento
  validates :placa, uniqueness: { case_sensitive: false,
                                 message:'El Vehículo ya pertenece a una flota' }
  validates :placa, length: { in: 6..7, message: 'La placa debe tener mínimo 6 y máximo 7 caracteres.' }

  enum tipo_unidad: {  minibus: "Minibus",
                       autobus: "Autobus",
                       automovil: "Automovil",
                       rustico: "Rustico",
                       moto: "Moto",
                       microbus: "Microbus"
                            }

  def contrato_arrendamiento_update_or_create(attributes)
    self.contrato_arrendamiento || self.build_contrato_arrendamiento
    self.contrato_arrendamiento.update(attributes)
  end

  def self.build_vehiculo_intt(vehiculo_intt, contrato_arrendamiento_params, tramite_vehiculo_params, flota)
    propietario = TramitePropietario.find_by(NRO_TRAMITE: vehiculo_intt.NRO_TRAMITE) || TramitePropietario.new
    uso = Uso.find_by(ID_USO: vehiculo_intt.ID_USO) || Uso.new
    tipo_vehiculo = TipoVehiculo.find_by(ID_TIPO_VEHICULO: vehiculo_intt.ID_TIPO_VEHICULO) || TipoVehiculo.new
    marca = Marca.find_by(ID_MARCA: vehiculo_intt.ID_MARCA) || Marca.new
    vehiculo = Vehiculo.new(placa: vehiculo_intt.PLACA,
                             s_carroceria: vehiculo_intt.SERIAL_CARROCERIA,
                             ano: vehiculo_intt.ANO,
                             marca: marca.NOMBRE_MARCA,
                             modelo: vehiculo_intt.MODELO,
                             color: Color.color(vehiculo_intt.ID_COLOR1),
                             serial_motor: vehiculo_intt.SERIAL_MOTOR,
                             capacidad: vehiculo_intt.CAPACIDAD,
                             propietario: [propietario.PRIMER_NOMBRE,
                                           propietario.SEGUNDO_NOMBRE, propietario.PRIMER_APELLIDO, propietario.SEGUNDO_APELLIDO, propietario.NOMBRE_EMPRESA].reject(&:nil?).join(' '),
                             identificacion_propietario: [propietario.ID_TIPO_IDENTIFICACION,
                                                          propietario.NRO_IDENTIFICACION .to_s, propietario.DIGITO_RIF.to_s].reject(&:nil?).join(' '),
                             puesto: vehiculo_intt.NRO_PUESTOS,
                             uso: (uso.NOMBRE_USO || ''),
                             tipo_vehiculo: (tipo_vehiculo.NOMBRE_TIPO || ''  ),
                             flota: flota)
    vehiculo.build_contrato_arrendamiento(contrato_arrendamiento_params) unless contrato_arrendamiento_params.nil?

    vehiculo.build_seguro_vehiculo(tramite_vehiculo_params[:seguro_vehiculo]) if flota.seguro_vehiculo.nil?

    return vehiculo
  end

  # enum uso: { porpuesto: "Por Puesto",
  #             colectivo: "Colectivo",
  #             taxi: "Taxi",
  #             monotaxi: "Moto Taxi",
  #             escolar:"Escolar",
  #             periferico: "Periferico"
  # }
  #
end

app/helpers/vehiculos_helper.rb
module VehiculosHelper
end

app/views/vehiculos/vehiculos/_form_buscar_vehiculo.html.haml
.row
  .col-md-12
    .ibox.float-e-margins
      .ibox-title
        %h3
          Ingrese los datos del Vehículo
      .ibox-content
        .row
          .col-md-12
            /= form_for :tramite_vehiculo, method: :get, url: new_flota_vehiculo_path(@flota.id), html:{class:'form-horizontal m-t-mtd'} do |f|
            .form-horizontal.m-t-md
              = hidden_field_tag :f, params[:flota_id], id: 'flota_vehiculos_hi'
              .form-group
                =label_tag :placa, class: 'col-sm-4 control-label' do
                  Placa:
                  %span.fa.fa-asterisk.red
                .col-sm-6
                  =text_field_tag :placa, nil, class: 'form-control mayusculas',  maxlength: 7, id: 'placa_vehiculo'
              .form-group
                =label_tag :s_carroceria, class: 'col-sm-4 control-label' do
                  Serial de Carroceria:
                  %span.fa.fa-asterisk.red
                .col-sm-6
                  =text_field_tag :s_carroceria, nil,class: 'form-control mayusculas', id: 's_carroceria_vehiculo'
              -#.form-group
              -#  =label_tag :ano,'Año:', class: 'col-sm-4 control-label'
              -#  .col-sm-6
              -#    =text_field_tag :ano, nil,class: 'form-control mayusculas',  maxlength: 4, id: 'ano_vehiculo'
              .form-group
                .col-sm-3.col-sm-offset-7
                  /=submit 'Agregar vehículo', class: 'btn btn-success btn-block'
                  %button.btn.btn-success.btn-block#buscar_vehiculo
                    Buscar Vehículo
              %div.text-center#loading_buscar_vehiculo{style:'display:none;'}
                %br
                %br
                %h2 Buscando Vehículo
                %i.fa.fa-circle-o-notch.fa-5x.fa-spin
              #div_buscar_vehiculo

app/views/vehiculos/vehiculos/_vehiculo_in_quota.html.haml
.row
  %hr
  .col-md-9.col-md-offset-1
    %h4.text-center
      El número de Vehículos excede el cupo  asignado máximo para el servicio
.row
  %hr

app/views/vehiculos/vehiculos/_vehiculo_in_use.html.haml
.row
  %hr
  .col-md-9.col-md-offset-1
    %h4.text-center
      Vehículo ya asociado a una Operadora de Transporte
.row
  %hr

app/views/vehiculos/vehiculos/_vehiculo_no_carga.html.haml
.row
  %hr
  .col-md-9.col-md-offset-1
    %h4.text-center
      Placa o Serial de Carroceria no existe. Ingrese nuevamente.
.row
  %hr

app/views/vehiculos/vehiculos/_vehiculo_not_tipo.html.haml
.row
  %hr
  .col-md-9.col-md-offset-1
    %h4.text-center
      La tipología del vehículo no corresponde con la modalidad del servicio.
.row
  %hr

app/views/vehiculos/vehiculos/edit.html.haml
=provide(:title, 'Editar Vehículo')
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Vehículos de la flota
    %ol.breadcrumb
      = render_breadcrumbs :tag => :li

= render 'form',url_submit: flota_vehiculo_path(@flota,@vehiculo)

app/views/vehiculos/vehiculos/index.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-12
    %h2
      Vehículos de Flota
    %ol.breadcrumb
      = render_breadcrumbs :tag => :li

.wrapper.wrapper-content.animated.fadeInRight
  = render 'shared/info_servicio'
  = render 'shared/error_messages', object: @vehiculo, model: 'Vehiculo de Flota'
  - if @flota.vehiculos.any?
    = render 'form_buscar_vehiculo'
    .row
      .col-md-12.col-md-offset-0
        .ibox.float-e-margins
          .ibox-title
            %h3
              Vehículos Registrados
          .ibox-content
            %table.table.table-striped.table-bordered.table-condensed
              %thead
                %tr
                  %th
                    Placa
                  %th
                    Año
                  %th
                    Serial Carrocería
                  %th
                    Color
                  %th
                    Marca
                  %th
                    Uso
                  %th
                    Modelo
                  %th
                    Tipo
                  %th
                    Puestos
                  %th
                    Propietario
                  %th
                    C.I/RIF
                  %th
                    Vehículo En arriendo
                  %th{:colspan => '3'}
                    Acciones


              %tbody
                -@flota.vehiculos.each do |vehiculo_inttt|
                  %tr
                    %td
                      = vehiculo_inttt.placa
                    %td
                      = vehiculo_inttt.ano
                    %td
                      = vehiculo_inttt.s_carroceria
                    %td
                      = vehiculo_inttt.color
                    %td
                      = vehiculo_inttt.marca
                    %td
                      = vehiculo_inttt.uso
                    %td
                      = vehiculo_inttt.modelo
                    %td
                      = TipoVehiculo.tipo_vehiculo(vehiculo_inttt.tipo_vehiculo)
                    %td
                      = vehiculo_inttt.puesto
                    %td
                      = vehiculo_inttt.propietario
                    %td
                      = vehiculo_inttt.identificacion_propietario
                    %td.text-center
                      - unless vehiculo_inttt.contrato_arrendamiento.nil?
                        %i.fa.fa-check
                    %td
                      = link_to  flota_vehiculo_path(@flota, vehiculo_inttt), title: 'Ver', rel: 'tooltip' do
                        %i.fa.fa-search
                      = link_to  edit_flota_vehiculo_path(@flota,vehiculo_inttt), title: 'Editar', rel: 'tooltip' do
                        %i.fa.fa-pencil-square-o
                      = link_to  flota_vehiculo_path(@flota,vehiculo_inttt) , method: :delete,
                      data: { confirm:'¿Seguro de borrar Vehiculo de flota?' },  title: 'Eliminar', rel: 'tooltip' do
                        %i.fa.fa-trash-o

  - else
    .row
      .col-md-12.col-md-offset-0
        %ul.text-muted.leyenda
          %li.text-justify
            Por cada vehículo de la flota ingrese la placa del vehículo y presione
            %span.amarillo
              Agregar
          %li.text-justify
            Si desea guardar los datos del registro oprima
            %span.azul-oscuro
              Continuar
          %li.text-justify
            Si desea regresar al pantalla de inicio oprima
            %span.azul-claro
              Regresar
      .row
        .col-md-12.text-center
          %h3.font-bold No posee Vehículos
          .error-desc
            No posee vehículos asociados a la flota, puede registrar sus vehículos ingresando los datos solicitados a continuación.
          %br
    = render 'form_buscar_vehiculo'
  .row
    .col-md-12
      .ibox.float-e-margins
        .ibox-content
          .row
            .col-sm-3
              = link_to @url_wizard_prev, class: "btn btn-info btn-block" do
                %i.fa.fa-arrow-left
                Regresar
            .col-sm-3.col-sm-offset-6
              = link_to vehiculo_verificar_modalidad_path(id: @flota.id), class: "btn btn-success btn-block", remote: true do
                Guardar y Continuar
              -#= link_to 'Continuar', ruta_flota_index_path(id: @flota.id), class: "btn btn-success pull-right"

app/views/vehiculos/vehiculos/new.html.haml
=provide(:title, 'Nuevo Vehículo')
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-10
    %h2
      Vehículos de la flota
    %ol.breadcrumb
      = render_breadcrumbs :tag => :li
      -#%li
      -#  Inicio
      -#%li
      -#  Operadora
      -#%li
      -#  Servicios
      -#%li
      -#  Seguro
      -#%li.text-navy
      -#  %b
      -#    Nuevo Vehículo

= render 'form', url_submit: flota_vehiculos_path(@flota)

app/views/vehiculos/vehiculos/show.html.haml
.row.wrapper.border-bottom.white-bg.page-heading
  .col-lg-12
    %h2
      Vehículos de Flota
    %ol.breadcrumb
      = render_breadcrumbs :tag => :li

.wrapper.wrapper-content.animated.fadeInRight
  = render 'shared/info_servicio'
  .row
    .col-md-12.col-md-offset-0
      .ibox.float-e-margins
        .ibox-title
          %h3
            Vehículos de Flota / Datos del Vehículo
        .ibox-content
          .col-lg-12
            %h3
              Vehículo
          %table.table.table-striped.table-bordered.table-condensed
            %thead
              %tr
                %th
                  Placa
                %th
                  Serial de Carroceria
                %th
                  Modelo
                %th
                  Marca
                %th
                  Año
              %tbody
                %tr
                  %td
                    #{@vehiculo.placa}
                  %td
                    #{@vehiculo.s_carroceria}
                  %td
                    #{@vehiculo.modelo}
                  %td
                    #{@vehiculo.marca}
                  %td
                    #{@vehiculo.ano}
            %thead
              %tr
                %th
                  Color
                %th
                  Serial de Motor
                %th
                  Uso
                %th
                  Tipo
                %th
                  Capacidad
              %tbody
                %tr
                  %td
                    #{@vehiculo.color}
                  %td
                    #{@vehiculo.serial_motor}
                  %td
                    #{@vehiculo.uso}
                  %td
                    #{@vehiculo.tipo_vehiculo}
                  %td
                    #{@vehiculo.puesto}
              %thead
                %tr
                  %th{colspan:3}
                    Propietario
                  %th{colspan:2}
                    C.I/RIF
                %tbody
                  %tr
                    %td{colspan:3}
                      = @vehiculo.propietario
                    %td{colspan:2}
                      = @vehiculo.identificacion_propietario
          %br/
      - if @flota.seguro_vehiculo.nil?
        -#seguro particular
        .row
          .col-md-12.col-md-offset-0
            .ibox.float-e-margins
              .ibox-content
                .col-lg-12
                  %h3
                    Seguro Vehículo
                %table.table.table-striped.table-bordered.table-condensed
                  %thead
                    %tr
                      %th
                        Aseguradora
                      %th
                        Rif
                      %th
                        Número de Póliza
                      %th
                        Fecha de Vencimiento
                    %tbody
                      %tr
                        %td
                          #{@vehiculo.seguro_vehiculo.aseguradora.nombre}
                        %td
                          #{@vehiculo.seguro_vehiculo.aseguradora.rif}
                        %td
                          #{@vehiculo.seguro_vehiculo.num_poliza}
                        %td
                          #{@vehiculo.seguro_vehiculo.fecha_vencimiento}
      - else
        -#seguro colectivo
        .row
          .col-md-12.col-md-offset-0
            .ibox.float-e-margins
              .ibox-content
                .col-lg-12
                  %h3
                    Seguro Vehículo
                %table.table.table-striped.table-bordered.table-condensed
                  %thead
                    %tr
                      %th
                        Aseguradora
                      %th
                        Rif
                      %th
                        Número de Póliza
                      %th
                        Fecha de Vencimiento
                    %tbody
                      %tr
                        %td
                          #{@flota.seguro_vehiculo.aseguradora.nombre}
                        %td
                          #{@flota.seguro_vehiculo.aseguradora.rif}
                        %td
                          #{@flota.seguro_vehiculo.num_poliza}
                        %td
                          #{@flota.seguro_vehiculo.fecha_vencimiento}
            %br/
      - unless @vehiculo.contrato_arrendamiento.nil?
        -#contrato de arrendamiento
        .row
          .col-md-12.col-md-offset-0
            .ibox.float-e-margins
              .ibox-content
                .col-lg-12
                  %h3
                    Contrato de arrendamiento
                %table.table.table-striped.table-bordered.table-condensed
                  %thead
                    %tr
                      %th
                        Año(s) de Duración del Contrato
                      %th
                        Fecha del Contrato
                      %th
                        Nº Tomo
                      %th
                        Nº Folio
                      %th
                        Notaria
                    %tbody
                      %tr
                        %td
                          #{@vehiculo.contrato_arrendamiento.duracion}
                        %td
                          #{@vehiculo.contrato_arrendamiento.fecha}
                        %td
                          #{@vehiculo.contrato_arrendamiento.tomo}
                        %td
                          #{@vehiculo.contrato_arrendamiento.folio}
                        %td
                          #{@vehiculo.contrato_arrendamiento.notaria}
                    %thead
                      %tr
                        %th Nombre / Razón Social Arrendatario
                        %th Identificación Arrendatario
                    %tbody
                      %tr
                        %td
                          #{@vehiculo.contrato_arrendamiento.nombre_arrendatario}
                        %td
                          #{@vehiculo.contrato_arrendamiento.rif_arrendatario}
                  %br/

    .row
      .col-md-12
        .ibox.float-e-margins
          .ibox-content
            .row
              .col-sm-3
                = link_to flota_vehiculos_url(id: @flota.id), class: "btn btn-info btn-block" do
                  %i.fa.fa-arrow-left
                  Regresar
              .col-sm-6
              .col-sm-3
                = link_to  edit_flota_vehiculo_path(@flota,@vehiculo), class: 'btn btn-success btn-block' do
                  %i.fa.fa-pencil-square-o
                  Editar